CREATE USER 'zabbixmon'@'localhost' IDENTIFIED BY 'zabbixmon';
CREATE USER 'zabbixmon'@'127.0.0.1' IDENTIFIED BY 'zabbixmon';
GRANT USAGE,PROCESS,SHOW DATABASES,REPLICATION CLIENT,SELECT ON *.* TO 'zabbixmon'@'localhost';
GRANT USAGE,PROCESS,SHOW DATABASES,REPLICATION CLIENT,SELECT ON *.* TO 'zabbixmon'@'127.0.0.1';
