name: LinuxOnlyMySQL

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Update all binary'

jobs:
  github-job:
    name: Ubuntu (MySQL)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass libxml2-dev libssl-dev libcurl4-openssl-dev libpcre2-dev libconfig-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --with-mysql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd ${{ matrix.os }} mysql
        path: src/zabbix_agent/zabbix_agentd
  ol7-job:
    name: Oracle Linux 7 (MariaDB)
    runs-on: [self-hosted, linux, ol7]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --with-mysql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd ol7 maria
        path: src/zabbix_agent/zabbix_agentd
  debian9-job:
    name: Debian 9 (MariaDB)
    runs-on: [self-hosted, linux, debian9]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --with-mysql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd debian9 maria
        path: src/zabbix_agent/zabbix_agentd
  debian10-job:
    name: Debian 10 (MariaDB)
    runs-on: [self-hosted, linux, debian10]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --with-mysql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd debian10 maria
        path: src/zabbix_agent/zabbix_agentd
