name: Linux

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Update all binary'

jobs:
  ol7-job:
    name: Oracle Linux 7 (MariaDB, PgSQL)
    runs-on: [self-hosted, linux, ol7]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/aix 2>/dev/null
        rm -rf ./bin/rhel 2>/dev/null
        rm -rf ./bin/ubuntu 2>/dev/null
        rm -rf ./bin/win32/*.dll 2>/dev/null
        rm -rf ./bin/win32/*.exe 2>/dev/null
        rm -rf ./bin/win32/*.cmd 2>/dev/null
        rm -rf ./bin/win64/*.dll 2>/dev/null
        rm -rf ./bin/win64/*.exe 2>/dev/null
        rm -rf ./bin/win64/*.cmd 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles; chmod a+x ./create/bin/*.{sh,pl}
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Prepare build
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-openssl --with-libpthread --with-libpcre2 --with-libcurl --enable-dbmon --enable-dbmon-mysql --enable-dbmon-postgresql --with-mysql --with-postgresql=/usr/pgsql-10/bin/pg_config --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
        make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd ol7 maria pgsql
        path: src/zabbix_agent/zabbix_agentd
  ol7-oracle-job:
    name: Oracle Linux 7 (Oracle 18c)
    runs-on: [self-hosted, linux, ol7]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/aix_7.1 2>/dev/null
        rm -rf ./bin/ubuntu 2>/dev/null
        rm -rf ./bin/ubuntu_only_pgsql 2>/dev/null
        rm -rf ./bin/win32/*.dll 2>/dev/null
        rm -rf ./bin/win32/*.exe 2>/dev/null
        rm -rf ./bin/win32/*.cmd 2>/dev/null
        rm -rf ./bin/win64/*.dll 2>/dev/null
        rm -rf ./bin/win64/*.exe 2>/dev/null
        rm -rf ./bin/win64/*.cmd 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles; chmod a+x ./create/bin/*.{sh,pl}
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Prepare build
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-openssl --with-libpthread --with-libpcre2 --with-libcurl --enable-dbmon --enable-dbmon-oracle --with-oracle --with-oracle-lib=/u01/app/oracle/18c/dbhome_1/lib --with-oracle-include=/u01/app/oracle/18c/dbhome_1/rdbms/public --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
        make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd ol7 oracle18c
        path: src/zabbix_agent/zabbix_agentd
  debian9-job:
    name: Debian 9 (MariaDB, PgSQL)
    runs-on: [self-hosted, linux, debian9]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/aix_7.1 2>/dev/null
        rm -rf ./bin/ubuntu 2>/dev/null
        rm -rf ./bin/ubuntu_only_pgsql 2>/dev/null
        rm -rf ./bin/win32/*.dll 2>/dev/null
        rm -rf ./bin/win32/*.exe 2>/dev/null
        rm -rf ./bin/win32/*.cmd 2>/dev/null
        rm -rf ./bin/win64/*.dll 2>/dev/null
        rm -rf ./bin/win64/*.exe 2>/dev/null
        rm -rf ./bin/win64/*.cmd 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles; chmod a+x ./create/bin/*.{sh,pl}
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Prepare build
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-openssl --with-libpthread --with-libpcre2 --with-libcurl --enable-dbmon --enable-dbmon-mysql --enable-dbmon-postgresql --with-mysql --with-postgresql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
        make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd debian9 maria pgsql
        path: src/zabbix_agent/zabbix_agentd
  debian10-job:
    name: Debian 10 (MariaDB, PgSQL)
    runs-on: [self-hosted, linux, debian10]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/aix_7.1 2>/dev/null
        rm -rf ./bin/ubuntu 2>/dev/null
        rm -rf ./bin/ubuntu_only_pgsql 2>/dev/null
        rm -rf ./bin/win32/*.dll 2>/dev/null
        rm -rf ./bin/win32/*.exe 2>/dev/null
        rm -rf ./bin/win32/*.cmd 2>/dev/null
        rm -rf ./bin/win64/*.dll 2>/dev/null
        rm -rf ./bin/win64/*.exe 2>/dev/null
        rm -rf ./bin/win64/*.cmd 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles; chmod a+x ./create/bin/*.{sh,pl}
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Prepare build
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-openssl --with-libpthread --with-libpcre2 --with-libcurl --enable-dbmon --enable-dbmon-mysql --enable-dbmon-postgresql --with-mysql --with-postgresql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
        make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd debian10 maria pgsql
        path: src/zabbix_agent/zabbix_agentd
