name: LinuxOnlyOracle

on:
#  schedule:
#    - cron: "0 18 * * 1-5"
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Update all binary'

jobs:
  ol7-oracle-job:
    name: Oracle Linux 7 (Oracle 18c)
    runs-on: [self-hosted, linux, ol7]
    steps:
    - uses: actions/checkout@v2
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Extract distr
      run: tar -zxf zabbix-5.0.2.tar.gz
    - name: Change directory
      run: cd zabbix-5.0.2/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-oracle --with-oracle --with-oracle-lib=/u01/app/oracle/18c/dbhome_1/lib --with-oracle-include=/u01/app/oracle/18c/dbhome_1/rdbms/public --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd ol7 oracle18c
        path: src/zabbix_agent/zabbix_agentd
