name: Release

on:
#  push:
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Create new release'

jobs:
  github-job-release:
    name: Ubuntu
    runs-on: [ubuntu-18.04]
    steps:
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass default-jdk libxml2-dev libssl-dev libcurl4-openssl-dev libsnmp-dev libevent-dev libsqlite3-dev libpcre2-dev libssh2-1-dev libopenipmi-dev unixodbc-dev libldap2-dev libconfig-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/aix_7.1 2>/dev/null
        rm -rf ./bin/ubuntu 2>/dev/null
        rm -rf ./bin/ubuntu_only_pgsql 2>/dev/null
        rm -rf ./bin/win32/*.dll 2>/dev/null
        rm -rf ./bin/win32/*.exe 2>/dev/null
        rm -rf ./bin/win32/*.cmd 2>/dev/null
        rm -rf ./bin/win64/*.dll 2>/dev/null
        rm -rf ./bin/win64/*.exe 2>/dev/null
        rm -rf ./bin/win64/*.cmd 2>/dev/null
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.ZABBIX_VERSION }}
        release_name: Zabbix v${{ env.ZABBIX_VERSION }} (unofficial) now released
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
        asset_name: zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
        asset_content_type: application/gzip
