name: TestBuildOnLinux

on:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - ".github/**"
#      - "bin/**"
#      - "build/**"
#      - "conf/**"
#      - "create/**"
#      - "database/**"
#      - "man/**"
#      - "misc/**"
#      - "packages/**"
#      - "sass/**"
#      - "templates/**"
#      - "tests/**"
#      - "ui/**"
#      - "vs2017/**"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run test build'

jobs:
  github-job:
    name: Ubuntu (MySQL, PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass libxml2-dev libssl-dev libcurl4-openssl-dev libpcre2-dev libconfig-dev
        sudo apt-get install -y dpkg-dev devscripts git dh-make build-essential autoconf autotools-dev quilt pkg-config tar xz-utils curl
        sudo apt-get install -y libmysqlclient-dev libpq-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Prepare build
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Build
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --enable-dbmon-postgresql --with-mysql --with-postgresql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
        make
        ./src/zabbix_agent/zabbix_agentd_dbmon -V
