name: TestBuildOnLinux

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "bin/**"
      - "build/**"
      - "conf/**"
      - "create/**"
      - "database/**"
      - "man/**"
      - "misc/**"
      - "packages/**"
      - "sass/**"
      - "templates/**"
      - "tests/**"
      - "ui/**"
      - "vs2017/**"

jobs:
  github-job:
    name: Ubuntu (MySQL, PgSQL)
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install base dependencies
      run: sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass libxml2-dev libssl-dev libcurl4-openssl-dev libpcre2-dev libconfig-dev
    - name: Install database dependencies
      run: sudo apt-get install -y libmysqlclient-dev libpq-dev
    - name: Run bootstrap
      run: ./bootstrap.sh
    - name: Run configure
      run: ./configure
    - name: Build dbschema
      run: make dbschema
    - name: Build gettext
      run: make gettext
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build css
      run: make css
    - name: Build dist
      run: make dist
    - name: Get current Zabbix version
      run: echo "::set-env name=ZABBIX_VERSION::$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')"
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Change directory
      run: cd zabbix-${{ env.ZABBIX_VERSION }}/
    - name: Run configure
      run: ./configure --with-openssl --with-libpthread --with-libpcre --with-libcurl --enable-dbmon --enable-dbmon-mysql --enable-dbmon-postgresql --with-mysql --with-postgresql --enable-ipv6 --enable-agent --sysconfdir=/etc/zabbix
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: zabbix_agentd v${{ env.ZABBIX_VERSION }} (ubuntu-18.04 mysql pgsql)
        path: src/zabbix_agent/zabbix_agentd
