name: CreateUbuntuPgSQLDEBSelf

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Create Ubuntu packages'

jobs:
  ubuntu-trusty-pg:
    name: Ubuntu (Trusty)
    runs-on: [self-hosted, linux, ubuntu-trusty]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/* 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Set variables
      run: |
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Prepare build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        cat include/version.h | sed "s@define ZABBIX_VERSION_REVISION@define ZABBIX_VERSION_REVISION ${GITHUB_SHA_SHORT}@g" > include/version.h.new
        mv include/version.h.new include/version.h
        cat src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java | sed "s@REVISION = \"\";@REVISION = \"${GITHUB_SHA_SHORT}\";@g" > src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new
        mv src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java
        cat src/go/pkg/version/version.go | sed "s@ZABBIX_VERSION_REVISION = \"\"@ZABBIX_VERSION_REVISION = \"${GITHUB_SHA_SHORT}\"@g" > src/go/pkg/version/version.go.new
        mv src/go/pkg/version/version.go.new src/go/pkg/version/version.go
        cp "../packages/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s).tar.gz" ubuntu.tar.gz
        tar -zxf ubuntu.tar.gz
        dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        dpkg-buildpackage -b -k${{ secrets.DBMON_GPG_KEYID }}
    - name: Upload deb from dev server
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        scp ../*.deb ${{ secrets.DBMON_REPO_SERVER_USER }}@${{ secrets.DBMON_REPO_SERVER }}:zabbix-dbmon/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s)/
    - name: Cleaning up workspace path
      run: |
        rm -rf "$GITHUB_WORKSPACE/zabbix-${{ env.ZABBIX_VERSION }}" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.deb" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.ddeb" 2>/dev/null
  ubuntu-xenial-pg:
    name: Ubuntu (Xenial)
    runs-on: [self-hosted, linux, ubuntu-xenial]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/* 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Set variables
      run: |
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Prepare build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        cat include/version.h | sed "s@define ZABBIX_VERSION_REVISION@define ZABBIX_VERSION_REVISION ${GITHUB_SHA_SHORT}@g" > include/version.h.new
        mv include/version.h.new include/version.h
        cat src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java | sed "s@REVISION = \"\";@REVISION = \"${GITHUB_SHA_SHORT}\";@g" > src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new
        mv src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java
        cat src/go/pkg/version/version.go | sed "s@ZABBIX_VERSION_REVISION = \"\"@ZABBIX_VERSION_REVISION = \"${GITHUB_SHA_SHORT}\"@g" > src/go/pkg/version/version.go.new
        mv src/go/pkg/version/version.go.new src/go/pkg/version/version.go
        cp "../packages/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s).tar.gz" ubuntu.tar.gz
        tar -zxf ubuntu.tar.gz
        dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        dpkg-buildpackage -b -k${{ secrets.DBMON_GPG_KEYID }}
    - name: Upload deb from dev server
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        scp ../*.deb ${{ secrets.DBMON_REPO_SERVER_USER }}@${{ secrets.DBMON_REPO_SERVER }}:zabbix-dbmon/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s)/
    - name: Cleaning up workspace path
      run: |
        rm -rf "$GITHUB_WORKSPACE/zabbix-${{ env.ZABBIX_VERSION }}" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.deb" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.ddeb" 2>/dev/null
  ubuntu-bionic-pg:
    name: Ubuntu (Bionic)
    runs-on: [self-hosted, linux, ubuntu-bionic]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/* 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Set variables
      run: |
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Prepare build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        cat include/version.h | sed "s@define ZABBIX_VERSION_REVISION@define ZABBIX_VERSION_REVISION ${GITHUB_SHA_SHORT}@g" > include/version.h.new
        mv include/version.h.new include/version.h
        cat src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java | sed "s@REVISION = \"\";@REVISION = \"${GITHUB_SHA_SHORT}\";@g" > src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new
        mv src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java
        cat src/go/pkg/version/version.go | sed "s@ZABBIX_VERSION_REVISION = \"\"@ZABBIX_VERSION_REVISION = \"${GITHUB_SHA_SHORT}\"@g" > src/go/pkg/version/version.go.new
        mv src/go/pkg/version/version.go.new src/go/pkg/version/version.go
        cp "../packages/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s).tar.gz" ubuntu.tar.gz
        tar -zxf ubuntu.tar.gz
        dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        dpkg-buildpackage -b -k${{ secrets.DBMON_GPG_KEYID }}
    - name: Upload deb from dev server
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        scp ../*.deb ${{ secrets.DBMON_REPO_SERVER_USER }}@${{ secrets.DBMON_REPO_SERVER }}:zabbix-dbmon/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s)/
    - name: Cleaning up workspace path
      run: |
        rm -rf "$GITHUB_WORKSPACE/zabbix-${{ env.ZABBIX_VERSION }}" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.deb" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.ddeb" 2>/dev/null
  ubuntu-focal-pg:
    name: Ubuntu (Focal)
    runs-on: [self-hosted, linux, ubuntu-focal]
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Delete old binary
      run: |
        rm -rf ./bin/* 2>/dev/null
        rm -f ./include/version.h.win 2>/dev/null
    - name: Run create bin, img and styles directory
      run: mkdir -p ./bin/win32/dev ./bin/win64/dev ./ui/assets/img ./ui/assets/styles
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
        make dbschema
        make gettext
        make css
        make dist
    - name: Set variables
      run: |
        echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Extract distr
      run: tar -zxf zabbix-${{ env.ZABBIX_VERSION }}.tar.gz
    - name: Prepare build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        cat include/version.h | sed "s@define ZABBIX_VERSION_REVISION@define ZABBIX_VERSION_REVISION ${GITHUB_SHA_SHORT}@g" > include/version.h.new
        mv include/version.h.new include/version.h
        cat src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java | sed "s@REVISION = \"\";@REVISION = \"${GITHUB_SHA_SHORT}\";@g" > src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new
        mv src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java.new src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java
        cat src/go/pkg/version/version.go | sed "s@ZABBIX_VERSION_REVISION = \"\"@ZABBIX_VERSION_REVISION = \"${GITHUB_SHA_SHORT}\"@g" > src/go/pkg/version/version.go.new
        mv src/go/pkg/version/version.go.new src/go/pkg/version/version.go
        cp "../packages/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s).tar.gz" ubuntu.tar.gz
        tar -zxf ubuntu.tar.gz
        dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      env:
        GO111MODULE: on
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        dpkg-buildpackage -b -k${{ secrets.DBMON_GPG_KEYID }}
    - name: Upload deb from dev server
      working-directory: ./zabbix-${{ env.ZABBIX_VERSION }}
      run: |
        scp ../*.deb ${{ secrets.DBMON_REPO_SERVER_USER }}@${{ secrets.DBMON_REPO_SERVER }}:zabbix-dbmon/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s)/
    - name: Cleaning up workspace path
      run: |
        rm -rf "$GITHUB_WORKSPACE/zabbix-${{ env.ZABBIX_VERSION }}" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.deb" 2>/dev/null
        rm -f "$GITHUB_WORKSPACE/*.ddeb" 2>/dev/null
