name: CreateUbuntuPgSQLDEB

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Create Ubuntu packages'

jobs:
  github-job:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y autoconf automake gcc make wget unzip gettext sass libxml2-dev libssl-dev libcurl4-openssl-dev libpcre2-dev libconfig-dev
        sudo apt-get install -y dpkg-dev devscripts git dh-make build-essential autoconf autotools-dev quilt pkg-config tar xz-utils curl
        sudo apt-get install -y libmysqlclient-dev libpq-dev
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Build zabbix dist
      run: |
        ./bootstrap.sh
        ./configure
         make dist
         echo "ZABBIX_VERSION=$(cat configure | grep PACKAGE_VERSION= | cut -d = -f2 | tr -d \')" >> $GITHUB_ENV
    - name: Prepare build DEB
      run: |
        cp "packages/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s).tar.gz" ubuntu.tar.gz && tar -zxf ubuntu.tar.gz
        dch -v "1:${{ env.ZABBIX_VERSION }}-1+$(lsb_release -c -s)" --distribution "$(lsb_release -c -s)" "Release ${{ env.ZABBIX_VERSION }}"
    - name: Build DEB
      run: dpkg-buildpackage -b
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DBMON_REPO_SERVER_PRIVATE_KEY }}
        known_hosts: ${{ secrets.DBMON_REPO_SERVER_KNOWN_HOSTS }}
    - name: Upload deb from dev server
      run: scp ../*.deb ${{ secrets.DBMON_REPO_SERVER_USER }}@${{ secrets.DBMON_REPO_SERVER }}:zabbix-dbmon/$(lsb_release -i -s | tr '[:upper:]' '[:lower:]')_only_pgsql/$(lsb_release -c -s)/
